### ISSUE TITLE
This code won't compile on Windows

### ISSUE THREAD

**Issue by Damianoux** [haldean/ndef#1]
The problem is the omitted keyword "struct" and the return type of the two functions  ndef_destroy_buffer and ndef_destroy.

You shoud change the function prototype:

in ndef.h

void ndef_destroy_buffer(struct ndef_record*);
void ndef_destroy(struct ndef_record*);

in ndef.c

void ndef_destroy_buffer(struct ndef_record* record) {
...
}

void ndef_destroy(struct ndef_record* record) {
...
}

**Comment by haldean** [comment]
ok
